# Generated by Django 3.1 on 2021-01-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_auto_20210109_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=100)),
                ('website', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterField(
            model_name='time',
            name='end_time',
            field=models.CharField(choices=[('17:30', '17:30'), ('10:30', '10:30'), ('12:00', '12:00'), ('15:30', '15:30'), ('09:00', '09:00')], default='09:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.CharField(choices=[('10:30', '10:30'), ('07:30', '07:30'), ('14:00', '14:00'), ('16:00', '16:00'), ('09:00', '09:00')], default='07:30', max_length=5),
        ),
    ]
