# Generated by Django 3.1 on 2021-01-09 14:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_auto_20210109_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('student_number', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.day'),
        ),
        migrations.AlterField(
            model_name='location',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.room'),
        ),
        migrations.AlterField(
            model_name='location',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.time'),
        ),
        migrations.AlterField(
            model_name='room',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.faculty'),
        ),
        migrations.AlterField(
            model_name='time',
            name='end_time',
            field=models.CharField(choices=[('12:00', '12:00'), ('17:30', '17:30'), ('15:30', '15:30'), ('10:30', '10:30'), ('09:00', '09:00')], default='09:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.CharField(choices=[('07:30', '07:30'), ('14:00', '14:00'), ('10:30', '10:30'), ('09:00', '09:00'), ('16:00', '16:00')], default='07:30', max_length=5),
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(validators=[django.core.validators.MinValueValidator(20.0), django.core.validators.MaxValueValidator(0)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lms.location'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.professor'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='lms.StudentCourse', to='lms.Student'),
        ),
    ]
