# Generated by Django 3.1 on 2021-01-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_auto_20210109_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='mail',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='end_time',
            field=models.CharField(choices=[('10:30', '10:30'), ('12:00', '12:00'), ('15:30', '15:30'), ('09:00', '09:00'), ('17:30', '17:30')], default='09:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.CharField(choices=[('10:30', '10:30'), ('14:00', '14:00'), ('07:30', '07:30'), ('09:00', '09:00'), ('16:00', '16:00')], default='07:30', max_length=5),
        ),
    ]
